### ISSUE TITLE
Is connection following mutually exclusive with -m MAC filtering?

### ISSUE THREAD

**Issue by jsmif** [nccgroup/Sniffle#65]
On the front page it says:  
"Support for **capturing advertisements** from a target MAC on all three primary advertising channels using a single sniffer. This makes connection detection nearly 3x more reliable than most other sniffers that only sniff one advertising channel." (I added the emphasis)

I'm noticing two things right now:

1) Sniffle seems to be missing the connection packet between two test devices with very high probability right now. I thought it was completely broken until I added the -c option and sniffed on only one channel and then disconnected and reconnected a bunch of times until Sniffle eventually caught and followed the connection. So I must have just been getting unlucky before.

2) In the above statement, it says **capturing advertisements** on all 3 primary advertisement channels can be achieved somehow in parallel with this hardware. Is that limited to advertisements only, and excluding CONNECT_IND? Because when I use the -m option, I do certainly see advertisements from the target peripheral, but then when I connect to it, there is no connection following going on (also confirmed by examining the pcap.)

So I'm wondering, to reliably catch and follow connections, do I still actually need 3 pieces of Sniffle-compatible hardware, each of which is set to one of the advertising channels?

**Comment by sultanqasim** [comment]
What it does with the MAC filtering is that it listens for advertisements on channel 37, and if no CONNECT_IND is observed on channel 37 after an advertisement, it hops to channel 38 and waits a moment, and then hops to channel 39. In quiet RF environments, it can detect connection establishment fairly reliably. In environments with lots of BLE scanners, the hop timing for advertisers changes and it can miss connection establishment, so this is probably what was happening for you. At some point I want to look into ways to improve this to better handle the presence of many scanners, though it's tricky because of the very tight timing and latencies I have to work around.

**Comment by sultanqasim** [comment]
Let me know if the latest firmware (with 15ba641184c59abc4f32a941cdc2096b77ebba6e) improves connection detection reliability at all for you (when in the MAC filter mode with hopping between the three primary advertising channels). At least for me, the latest firmware is around 80-90% reliable at connection detection, where connection establishment can happen on any of the three primary advertising channels.

**Comment by sultanqasim** [comment]
I made some further improvements to connection detection reliability in advertiser hop mode, particularly on channel 38. In my limited testing with a few devices, I got greater than 90% connection detection reliability. Let me know how the latest firmware does for you.

**Comment by sultanqasim** [comment]
Here you go: https://github.com/nccgroup/Sniffle/releases/tag/dev-2024-04-07

**Comment by sultanqasim** [comment]
You can try now, I fixed the timeout related bug (saying it again so you get notified)

**Comment by sultanqasim** [comment]
Fresh build of the latest test firmware: https://github.com/nccgroup/Sniffle/releases/tag/dev-2024-04-09

**Comment by sultanqasim** [comment]
Thanks for testing. I deleted that development tag as the v1.8 release is newer and better.

 There's no such regression regarding receiving only on 37, but what is happening is that your peripheral  is behaving a bit differently than other peripherals I've used Sniffle with. Almost all peripherals I've encountered transmit an advertisement on channel 37 (and then listen for a CONNECT_IND or SCAN_REQ), then on 38 after a 300-500 us gap, then on 39 after a similar gap. Sniffle exploits this behaviour to capture connection requests on any of the three advertising channels by waiting for an advertisement on channel 37 targeting the right MAC, waiting a little more for CONNECT_IND on 37 if it comes, then hopping to 38, waiting a bit for CONNECT_IND, and then hopping to 39 for a few more milliseconds.

According to the Bluetooth Core Specification, the time between advertising on one primary advertising channel (like 37) and the next (like 38) within an advertising event must be less than 10 ms, but it is no more prescriptive than that, so in theory there can be much longer waits between channels. However, I've never seen such devices; all devices I've examined switch to the next advertising channel within a few hundred microseconds. Thus, Sniffle also assumes that the time between advertising on 37, 38, and 39 is short (a few hundred microseconds).

Bluetooth Core Specification 5.1 made a somewhat frustrating change (for sniffers)  where the advertising hop sequence does not need to be strictly 37, 38, 39, and can instead be any random sequence that can also change every connection event. See page 9 of <https://davidhoglund.typepad.com/files/1901_feature_overview_brief_final.pdf>. This completely breaks Sniffle's expectations regarding advertiser channel hop sequence, and thus breaks receiving connection requests on channels other than 37 in hopping mode. Given the limitations of the CC26x2 hardware (and similar low cost devices) that can only sniff one channel at a time, if the advertising hop sequence is truly random, one can never reliably capture connection requests on all channels tuning into just one at a time. However, if it were truly random, you would at least see scan requests on other channels sometimes. Fortunately, in practice, most Bluetooth 5.1/5.2/5.3 devices I've encountered still keep on following the old 37->38->39 sequence, and also for extended advertising this doesn't matter since the connection requests happens on an auxiliary (secondary advertising) channel.

I can imagine two possibilities for why the advertising hop mode is not working with your peripheral:

1. Your peripheral is waiting a long time (several milliseconds) between advertising on successive channels (like 37->38->39).
2. Your peripheral is taking the Bluetooth 5.1+ liberty of not following a 37->38->39 advertising hop sequence, and instead using some other (possibly fixed) hop sequence, such as 38->37->39 or 37->39->38.

Either of these situations could be causing the behaviour you described, though I'm not sure which of the two it is. When I have time, I could make you a firmware build that could help figure out which of the two (or both) situations is happening.

**Comment by sultanqasim** [comment]
Thanks for the additional information. Looking at the code for that Zephyr example and what it calls into, it just asks the HCI to do legacy advertising. The advertising channel sequence and timing of transmission between the three advertising channels is left up to the Nordic controller. I'm curious what the Nordic controller is doing, maybe I'll try to test that myself some day when I have time.

My guess is that it's hopping consistently in an unchanging sequence that's not 37->38->39. This guess is based on you never seeing any packets on channels 38 or 39 in advertising hop mode. If that's indeed the case, then I could just add an option to Sniffle to change the channel hop sequence in which is sniffs for advertisements.

However, if it's randomized for every connection event (technically permissible with Bluetooth 5.1 and up), then unfortunately there's nothing I can do.

I'll leave this issue open so that we can follow up in case either of us has a chance to figure out what the Nordic controller is doing.

**Comment by sultanqasim** [comment]
One other thing I'll add: If it turns out that Nordic's controller is choosing a particular randomized advertising hop sequence once (at boot? or based on some static identifier?), and then sticking with the same sequence for every advertising event, then I could implement a feature to figure out this hop sequence and then automatically use it.

**Comment by sultanqasim** [comment]
Thanks for testing that. This matches the behaviour you were reporting, and it's good they're not changing the order between advertising events. In that case, I will implement a feature to choose the advertising hop sequence, and an auto-detect feature to figure out the hop sequence.

**Comment by sultanqasim** [comment]
One thing to be aware about though is that time synchronization between multiple Sniffle sniffers is not microsecond level precise. They could be millisecond off, so comparing microsecond level timestamps like that isn't reliable. I was looking at the Zephr LE controller implementation, and it looked like it's just hopping in sequence 37->38->39 (just like every other controller I've seen in the past). See https://github.com/zephyrproject-rtos/zephyr/blob/5841c11cae6a569678a9533e2b96b51ec140008a/subsys/bluetooth/controller/ll_sw/nordic/lll/lll_adv.c#L1460

If that's indeed the case, then the other possibility is hop timing being different from what I expect, for example maybe it hops from 37 to 38 quicker than I'm expecting.

I've ordered a nRF52840 USB dongle, I'll do some experimentation to figure out what's going on, and devise a plan accordingly.

I know that Broadcom and TI both decided not to implement Randomized Advertising Channel Indexing, and at least last time I checked, Nordic also wasn't implementing it in their controller (see <https://devzone.nordicsemi.com/f/nordic-q-a/92540/randomized-advertising-channel-indexing> and <https://devzone.nordicsemi.com/f/nordic-q-a/66621/advertising-channel-sequence>).

Maybe Zephyr is doing something different from what I'm seeing right now in the code, or maybe it's just a matter of hop timing. I'll see when the Nordic dongles get delivered and I have some time to experiment.

Thanks again @jsmif for your time investigating this.

**Comment by sultanqasim** [comment]
Ah, yes that doesn't surprise me given your fast hop rate. With the -a option, it immediately triggers a hop to 38 after the firmware receives an ad on 37. However, the firmware gets it 130-150 us after the radio, and it takes another 200+ us to tune the radio to a new channel and start listening. Since your device advertises on 38 just 292 us after the end of the ad on 37 (faster than any other Bluetooth controller I've ever encountered), the Sniffle hardware is just not fast enough to catch the ad on 38. However, it will still catch CONNECT_IND PDUs on 38 and 39.

With regards to the -m option, the way it works is that without the option, it just sits on one channel. It only hops if a MAC filter is specified to say which target MAC to hop along with. With the -m option but no -a option, it will catch CONNECT_IND and SCAN_REQ/SCAN_RSP PDUs on 38 and 39. The -a option is intended to show the ads on 38 and 39, and works with every controller implementation used by devices I have (where there is a 370+ us gap between the end of the ad on 37 and the start of the ad on 38), though it won't work with your device because of the fast hopping.
