### ISSUE TITLE
Preliminary questions before commitment of Sniffle

### ISSUE THREAD

**Issue by joma74** [nccgroup/Sniffle#9]
Currently we are after decent audio bluetooth pairs of devices on a consumer level. Such pairs are mainly in-ears and mobiles with android/ios. On our way about the how and why of such pairs we were pretty disenchanted, missing a lot of reasonable information from the vendors.
Without diving too deep into the Bluetooth workings or crafting software ourselves, we would like to learn more with the help of your package plus a CC1352R1 TI board, within the above described context. 
Would appreciate if you advise us if answers to the following questions are possible regarding usage of Sniffle. Also, for additional workflow hints regarding tools before and thereafter along the questions, we thank you in advance.

Regarding connection details finding out
- [ ] Which BT protocol and version are negotiated between devices
- [ ] Which BT Profiles are negotiated between devices
- [ ] Which protocol is negotiated between devices
- [ ] Which codecs are used, especially any along the following: sbc, mpeg3, ldac, aptx(hd, ll, ad), lhdc in mono, stereo, dual, joint stereo.
- [ ] Which bitrate(kbps) are used between devices
- [ ] Which samplerate(kHz) are used between devices
- [ ] Possibility to trace any manual changes on either side of the devices

Regarding transmission details finding out
- [ ] What happens on loss of connection
- [ ] What happens on dropouts of transmission(on the audio stream, packet loss) 
- [ ] Possibility to analyze jitter regarding latency or rate error

**Comment by sultanqasim** [comment]
This would be an interesting thing to examine, however Sniffle is probably not the right tool for the job right now. While the LE Audio specification is coming out in conjunction with Bluetooth 5.2, and in the future headphones will make use of it, all current Bluetooth Audio devices use A2DP over Bluetooth Classic - essentially Bluetooth 2.1 and older. Sniffle only supports Bluetooth LE, not Classic. I do plan on eventually supporting the isochronous connection features of Bluetooth 5.2 that are used for LE audio, but devices using this are at least an year out.

Unfortunately, there are no good cheap sniffers for Bluetooth Classic. The only cheap BT Classic sniffer I'm aware of is the Ubertooth, but it only supports basic rate (1M) and its classic support is very crude. There are limited low cost options due to a combination of somewhat uncommon modulation for the EDR modes, fast channel hopping (tight timing requirements), and limited interest in putting in new development effort for a legacy protocol that is being replaced.

For sniffing A2DP over Bluetooth Classic, you'd probably be best off with a commercial sniffer from Ellisys or Teledyne-Lecroy/Frontline.
